### ISSUE TITLE
Meeting 11-19

### ISSUE THREAD

**Issue by jameslgithub** [Prakshal-Jain/NFTY#8]
**Front-end**
- Login 
- Sign Up 
- Options
- Marketplace

**Backend**
- Docker connection with frontend
- Port routing
- Database/Sign Up

**Comment by Prakshal-Jain** [comment]
I resolved all these issues (except the database stuff). Teammates, please check these on your end, and close this issue accordingly.
Thanks.

**Comment by stirfrysushi** [comment]
These issues were resolved by Prakshal, thank you!
